CREATE INDEX idx_name_a ON PRODUCTS (CASE WHEN NAME LIKE '%a%' THEN 1 ELSE NULL END);
CREATE INDEX DOC_DOC_DATE ON DOCUMENTS (DOCUMENT_DATE);
CREATE BITMAP INDEX CONTRACTORS_COUNTRY ON CONTRACTORS (COUNTRY);
CREATE INDEX PLIST_VALID_DATE ON PRICE_LISTS (VALID_DATE);
CREATE INDEX PRODUCTS_SPEC_LGTH ON PRODUCTS (LENGTH(SPECIFICATION));