UPDATE CONTRACTORS C
SET C.BUSINESS_NUMBER = 'NewBusinessNumber', C.COUNTRY = 'NewCountry'
WHERE C.ID IN (
    SELECT DISTINCT D.CONTRACTOR_FK
    FROM DOCUMENTS D
    JOIN USERS U ON D.CLIENT_FK = U.ID
    JOIN DOCUMENT_TYPES DT ON D.DOCUMENT_TYPE_FK = DT.ID
    JOIN WAREHOUSES W ON U.WAREHOUSE_FK = W.ID
    JOIN PRODUCTS P ON D.CONTRACTOR_FK = P.CONTRACTOR_FK
    WHERE D.DOCUMENT_DATE >= SYSDATE - 180
    AND DT.ABBREVIATION = 'dcel'
    AND U.NAME LIKE 'John%'
    AND W.ADDRESS LIKE '%Los Angeles%'
    AND P.PRODUCT_LENGTH < 50 -- Dodatkowe łączenie do tabeli PRODUCTS
    GROUP BY D.CONTRACTOR_FK
    HAVING COUNT(D.ID) > 3
)
AND C.COUNTRY = 'OldCountry';