UPDATE PRICE_LISTS
SET SALE = SALE * 1.1, -- Zwiększ cenę sprzedaży o 10%
    PURCHASE = (SELECT AVG(PURCHASE) FROM PRICE_LISTS) -- Ustaw średnią cenę zakupu
WHERE ID IN (
    SELECT PL.ID
    FROM PRICE_LISTS PL
    INNER JOIN PRODUCTS P ON P.ID = PL.PRODUCTS_FK
    WHERE P.PRODUCT_LENGTH > 100
    AND LENGTH(P.SPECIFICATION) < 500
);
