UPDATE PRICE_LISTS
SET SALE     = SALE * 1.1,
    PURCHASE = (SELECT AVG(PURCHASE) FROM PRICE_LISTS)
WHERE ID IN (SELECT PL.ID
             FROM PRICE_LISTS PL
                      INNER JOIN PRODUCTS P ON P.ID = PL.PRODUCTS_FK
             WHERE P.PRODUCT_LENGTH > 100
               AND LENGTH(P.SPECIFICATION) < 500);
